repos:
  # Black formatter
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args:
          - --line-length=88

  # isort import sorter
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0    # choose a version you want
    hooks:
      - id: isort
        args:
          - --profile
          - black
          - --line-length=88

  # Flake8 linter
#  - repo: https://github.com/pycqa/flake8
#    rev: 7.0.0     # pick version
#    hooks:
#      - id: flake8
#        args:
#          - --max-line-length=88
#          - --ignore=E203,E266,E501,W503
#          - --max-complexity=18

  # mypy type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2    # pick version
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
